const roscoData = [
    { letra: "A", respuesta: "Astro", definicion: "Empieza con A: Cuerpo celeste que puebla el universo." },
    { letra: "B", respuesta: "Barco", definicion: "Empieza con B: Vehículo flotante que se utiliza para transportarse por el agua." },
    { letra: "C", respuesta: "Cielo", definicion: "Empieza con C: Espacio en el que se mueven los astros y que por efecto visual parece rodear la Tierra." },
    { letra: "D", respuesta: "Diafragma", definicion: "Empieza con D: Abertura regulable en el objetivo de una cámara de fotos que controla la cantidad de luz." },
    { letra: "E", respuesta: "Enfoque", definicion: "Empieza con E: Ajuste que se hace en una cámara fotográfica para que la imagen se vea nítida." },
    { letra: "F", respuesta: "Futsal", definicion: "Empieza con F: Deporte similar al fútbol pero que se juega en una cancha de suelo rígido y dimensiones más reducidas." },
    { letra: "G", respuesta: "Gimnasio", definicion: "Empieza con G: Local cerrado y equipado con aparatos para hacer ejercicio físico y fortalecer los músculos." },
    { letra: "H", respuesta: "Horizonte", definicion: "Empieza con H: Línea aparente que separa el cielo y la tierra, ideal para fotografiar al atardecer." },
    { letra: "I", respuesta: "Isla", definicion: "Empieza con I: Porción de tierra rodeada de agua por todas partes, como el territorio compartido con Chile en el extremo sur." },
    { letra: "J", respuesta: "Juez", definicion: "Empieza con J: Persona que tiene autoridad para juzgar y sentenciar en una competición o tribunal." },
    { letra: "K", respuesta: "Karting", definicion: "Empieza con K: Disciplina del automovilismo que se practica con vehículos monoplaza sin techo ni suspensiones." },
    { letra: "L", respuesta: "Loica", definicion: "Empieza con L: Ave paseriforme sudamericana muy reconocible por el color rojo intenso de su pecho." },
    { letra: "M", respuesta: "Músculo", definicion: "Empieza con M: Órgano compuesto de fibras que se contrae para producir movimiento en el cuerpo." },
    { letra: "N", respuesta: "Naturaleza", definicion: "Empieza con N: Conjunto de todo lo que existe y está determinado por sus propias leyes, ideal para recorrer y disfrutar al aire libre." },
    { letra: "Ñ", respuesta: "Ñandú", definicion: "Empieza con Ñ: Ave corredora sudamericana, de gran tamaño, similar al avestruz." },
    { letra: "O", respuesta: "Objetivo", definicion: "Empieza con O: Lente o sistema de lentes de un instrumento óptico, como un 100-400mm." },
    { letra: "P", respuesta: "Pájaro", definicion: "Empieza con P: Animal vertebrado volador que muchas veces requiere un buen teleobjetivo para ser capturado en imagen." },
    { letra: "Q", respuesta: "Queso", definicion: "Empieza con Q: Alimento sólido que se obtiene por maduración de la cuajada de la leche." },
    { letra: "R", respuesta: "Río", definicion: "Empieza con R: Corriente natural de agua que fluye permanentemente, y que le da nombre a una ventosa ciudad fueguina." },
    { letra: "S", respuesta: "Susurro", definicion: "Empieza con S: Ruido suave y murmurado, un sonido muy utilizado para generar relajación antes de dormir." },
    { letra: "T", respuesta: "Trekking", definicion: "Empieza con T: Modalidad de excursionismo que consiste en recorrer a pie largas distancias por la montaña o escenarios naturales." },
    { letra: "U", respuesta: "Universo", definicion: "Empieza con U: Conjunto de todas las cosas creadas y el espacio que las contiene." },
    { letra: "V", respuesta: "Viento", definicion: "Empieza con V: Corriente de aire que se produce en la atmósfera, un fenómeno meteorológico muy característico de la Patagonia." },
    { letra: "W", respuesta: "Web", definicion: "Empieza con W: Red informática mundial, el lugar donde estás alojando el código de este juego." },
    { letra: "X", respuesta: "Xenón", definicion: "Empieza con X: Elemento químico gaseoso utilizado en lámparas e iluminación de alta intensidad." },
    { letra: "Y", respuesta: "Yema", definicion: "Empieza con Y: Parte central del huevo, de color amarillo." },
    { letra: "Z", respuesta: "Zoológico", definicion: "Empieza con Z: Lugar donde se cuidan y exhiben animales salvajes." }
];